trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: firstjob
    steps:
    - bash: echo Build First Job
  - job: secondjob
    steps:
      - bash: echo Build Second Job        
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployjob
    steps:
    - bash: echo Build DevDeploy Job
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployjob
    steps:
    - bash: echo Build QADeploy Job
- stage: PRodDeploy
  dependsOn:
  - Build
  - QADeploy
  jobs:
  - job: PRodDeployjob
    steps:
    - bash: echo Build PRodDeploy Job

